config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
	get '/dashboard' => 'welcome#dashboard'
	get '/yearview' => 'welcome#yearview'
  resources :accounts
  resources :debts
  resources :investments
  resources :users
  resources :incomes
  resources :monthly_spendings
	resources :months

	resources :calendars, only:[:index]

end

app/models/investment.rb
class Investment < ActiveRecord::Base
	belongs_to :investmentable, polymorphic: true
	has_many :advices, as: :from, dependent: :destroy
	has_many :advices, as: :to, dependent: :destroy

	before_create :round_to_two
	before_update :round_to_two

	def round_to_two
		self.amount = self.amount.round(2)
	end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController

	respond_to :json, only: [:index, :create, :update, :destroy]

	def index
		investments = current_user.investments.order('created_at ASC')
		respond_with investments
	end

	def create
		investment = current_user.investments.new(investment_params)
		investment.save!
		respond_with(investment)
	end

	def update
		investment = Investment.find params[:id]
		investment.update(investment_params)
		respond_with investment
	end

	def destroy
		investment = Investment.find(params[:id])
		investment.destroy
		respond_with investment
	end


	private

	def investment_params
		params.require(:investment).permit(:name, :amount, :interest_rate)
	end

	def set_user
		@user = current_user
	end

end

app/views/investments/_form.html.erb
<%= form_for @investment, remote:true do |f| %>
	<div>
		<div><%= f.label "Investment Account Name:" %></div>
		<%= f.text_field :name %>
	</div>
	<div>
		<div><%= f.label "Amount" %></div>
		<%= f.text_field :amount %>
	</div>
	<div>
		<div><%= f.label "Interest Rate" %></div>
		<%= f.text_field :interest_rate %>
	</div>
	<div>
		<%= f.submit %>
	</div>
<% end %>
<div class="render_here"></div>

app/views/investments/_investment.html.erb
<h3>Name: <%= @investment.name %> || Amount: <%= @investment.amount %> || Interest Rate: <%= @investment.interest_rate %> </h3>

app/views/investments/create.js.erb
$('.no_investment').fadeOut();
$('form').hide();
$('#new_investment_path').show();
$('#undo-new-investment').hide();
$('.render_create_here').append('<%= j render (@investment) %><div class="render_create_here"></div>')

app/views/investments/index.html.erb
<h1>Investment</h1>

<% if @user.investments.any? %>
	<% @user.investments.each do |investment| %>
		<h3>Name: <%= investment.name %> || Amount <%= investment.amount %> || Interest Rate: <%= investment.interest_rate %> </h3>
	<% end %>
<% else %>
	<h2 class="no_investment">No Investments Currently</h2>
<% end %>
<div class='render_create_here'></div>
<%= link_to 'Add An Investment', new_investment_path(), id:'new_investment_path', remote:true  %>
<div id="undo-new-investment">UNDO</div>
<div class='render_here'></div>


<h2> <%= link_to '<- Previous Step: Investments', debts_path %> | <%= link_to "Dashboard ->", user_path(current_user) %></h2>

app/views/investments/new.js.erb
$('.render_here').replaceWith('<%= j render("form") %>')
$('#new_investment_path').hide();
$('#undo-new-investment').show();


$(document).on("click", "#undo-new-investment", function(e){
  $('form').remove();
	$('#new_investment_path').show();
	$('#undo-new-investment').hide();
});