config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
	get '/dashboard' => 'welcome#dashboard'
	get '/yearview' => 'welcome#yearview'
  resources :accounts
  resources :debts
  resources :investments
  resources :users
  resources :incomes
  resources :monthly_spendings
	resources :months

	resources :calendars, only:[:index]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :months
  has_one :monthly_spending, as: :monthly_spendable
	has_one :cash_flow, as: :cash_flowable
  has_many :accounts, as: :accountable
  has_many :incomes, as: :incomeable
  # has_many :assets, as: :assetable
  has_many :debts, as: :debtable
  has_many :investments, as: :investmentable

  accepts_nested_attributes_for :accounts


  def total_monthly_spending
		values = monthly_spending.slice("rent", "food", "phone", "utilities", "everything_else").values
		values.reduce(:+)
  end

  def total_debt
		debts.any? ? debts.pluck(:amount).reduce(:+) : 0
  end

  def total_min_monthly_payments
		debts.any? ? debts.pluck(:minimum_monthly_payment).reduce(:+) : 0
  end

  def total_investment
		investments.any? ? add_and_average_investments : create_psuedo_investment
  end

	def add_and_average_investments
		total_amount = investments.pluck(:amount).reduce(:+)
		average_interest_rate = investments.pluck(:interest_rate).reduce(:+)/investments.length

		investment_hash = {amount: total_amount, interest_rate: average_interest_rate}
	end

	def create_psuedo_investment
		investment_hash = {amount: 0, interest_rate: 0.07 }
	end

  def total_monthly_income
    incomes.pluck(:source_amount).reduce(:+)
  end

  def user_cash_flow
    (total_monthly_income - total_monthly_spending) - total_min_monthly_payments
  end

  def three_months_spending
    total_monthly_spending * 3
  end

  def six_months_spending
    total_monthly_spending * 6
  end

  def savings
		accounts.where(a_type: "Savings").pluck(:amount).reduce(:+)
  end

	def hashitize_months
		options = {};
		monthz = months.map do |month|
			 MonthObj.new(month.attrs)
		end
		return monthz
	end

	def hash_calendar_months
		options = {}
		monthz = months.map do |month|
			CalendarMonth.new(month.all_totals)
		end
		return monthz
	end

 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user

	def show
		FinancialForcast::CalculationMatrix.new(current_user.months.first).call
	end

	def update
		@user.update_attributes(account_params)
		redirect_to new_monthly_income_path
	end

	private

	def set_user
		@user = current_user
	end

	def account_params
		params.require(:user).permit(accounts_attributes: [:id, :a_type, :amount, :interest_rate])
	end
end

app/views/users/show.html.erb
<center>
	<h1><%= @user.email %>'s Financial Docket</h1>
	<div class="portfolio_data">
		<div class="generalUserStats">
			<h2><u>Savings Account:</u></h2>
			$<%= @user.accounts.find_by(a_type:'Savings').amount %>

			<h2><u>Checking Account:</u></h2>
			$<%= @user.accounts.find_by(a_type:'Checkings').amount %>

			<h2><u><%= link_to "Total Debt", debts_path %>:</u></h2>
			$ <%= @user.total_debt %>
		</div>

		<ul>
			<% @user.debts.each do |debt| %>
				<li>Name: <%= debt.name %> || Amount: <%= debt.amount %> || Interest Rate: <%= debt.interest_rate %> || Minimum Monthly Payment: <%= debt.minimum_monthly_payment %> </li>
			<% end %>
		</ul>

		<h2><u><%= link_to "Total Investments", investments_path %>:</u></h2>
		$<%= @total_investment_amount %>
		<ul>
			<% @user.investments.each do |investment| %>
				<li>Name: <%= investment.name %> || Amount: <%= investment.amount %> || Interest Rate: <%= investment.interest_rate %> </li>
			<% end %>
		</ul>
	</div>
	<div class="monthly_numbers">
		<h2>Total Monthly Spending: </h2>
		<%= @user.total_monthly_spending %>

		<h2>Monthly Income:</h2>
		<%= @user.total_monthly_income %>
		<% @user.incomes.each do |income| %>
		<li>Name: <%= income.source_name %> || Amount <%= income.source_amount %></li>
		<% end %>

		<h2>Monthly CashFlow</h2>
		<%= @user.cash_flow %>
	</div>
</center>

<div class="fullCalendar">
	<% @months_from_now.each do |month| %>
		<% finance = CalculationMatrix.new(@user).financial_shuffle(@matrix_results[:debt], @matrix_results[:savings], @matrix_results[:total_investment], @user.cash_flow, []) %>
		<div class="individual_month">
			<div class="calendarMonth"><%= month %></div>
			<div class="calendarInformation">
				<div><strong>Savings</strong>: <%= @matrix_results[:savings] %></div>
				<div>
					<strong>Investments:</strong>
					 <%= @matrix_results[:total_investment][:amount] %>
				</div>
				<div>
					<u><strong>Advice</strong></u>
					<ul>
						<% @matrix_results[:advice].each do |advice| %>
							<li><%= advice %></li>
						<% end %>
					</ul>
				</div>
				<div>
					<strong>Debt:</strong> <%= @matrix_results[:debt] > 0 ? @matrix_results[:debt] : "NO MORE DEBT!"  %>
				</div>
			</div>
		</div>
			<% @matrix_results = finance %>

	<% end %>
</div>

<h1><%= link_to 'Sign Out YO!', destroy_user_session_path(current_user), method: :delete %></h1>